[package]
name = "xb-arb-finder"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
xb-types.path = "../../types"
