[package]
name = "xb-subscriber"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio-util.workspace = true
