[package]
name = "xb-order-executor"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
xb-types.path = "../types"
