[package]
name = "xb-cashout"
version.workspace = true
edition.workspace = true

[dependencies]
rust_decimal.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
xb-types.path = "../../types"
