[package]
name = "xb-types"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
rust_decimal.workspace = true
serde.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
test-case.workspace = true