[package]
name = "xb-exchanges-lbank"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
ezsockets.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
xb-types.path = "../../types"